using System;
using System.Globalization;
using System.Text;

namespace WinUIGallery.SourceGenerator;

internal static partial class StringBuilderExtensions
{
    internal static StringBuilder AppendFullHeader(this StringBuilder sb, string? fromData = null)
    {
        return sb.AppendAutoGeneratedHeader(fromData);
    }

    internal static StringBuilder AppendAutoGeneratedHeader(this StringBuilder sb, string? fromData = null)
    {
        if (string.IsNullOrEmpty(fromData))
        {
            return sb.AppendLine("/// <auto-generated/>");
        }
        else
        {
            sb.AppendLine("// -----------------------------------------------------------------------------------------------------");
            sb.AppendLine("// | <auto-generated>                                                                                  |");
            sb.AppendLine("// |    This code was generated by source generator.                                                   |");
            sb.AppendLine("// |                                                                                                   |");
            sb.AppendLine("// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |");
            sb.AppendLine("// | </auto-generated>                                                                                 |");
            sb.AppendLine("// |                                                                                                   |");
            sb.AppendLine("// |                            -------------------------------------------                            |");
            sb.AppendLine("// |                            |                                         |                            |");
            sb.AppendLine($"// |                            |   Date Modified: {DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture)}    |                            |");
            sb.AppendLine("// |                            |                                         |                            |");
            sb.AppendLine("// |                            -------------------------------------------                            |");
            sb.AppendLine("// -----------------------------------------------------------------------------------------------------");
            sb.AppendLine($"//Source files:");
            sb.AppendLine(fromData);
            sb.AppendLine();

            return sb;
        }
    }
}

