name: Feature request
description: Suggest a sample or enhancement for the WinUI Gallery
title: "Sample request title"
labels: ["needs-triage"]
body:
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Issue type
      options:
        - sample request
        - enhancement
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Which version of the app?
      options:
        - "WinUI 3 Gallery" 
        - "WinUI 2 Gallery"
  - type: textarea
    attributes:
      label: Description
      description: Please provide a description of the sample request or enhancement
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem
  - type: dropdown
    attributes:
      label: Windows version
      description: Which Windows versions did you see the issue on?
      multiple: true
      options:
        - Insider Build (xxxxx)
        - Windows 11 22H2 (22621)
        - Windows 11 21H2 (22000)
        - Windows 10 22H2 (19045)
        - November 2021 Update/21H2 (19044)
        - May 2021 Update/21H1 (19043)
        - October 2020 Update/20H2 (19042)
        - October 2018 Update/RS5 (17763)
  - type: textarea
    attributes:
      label: Additional context
      description: Enter any other applicable info here
